version: "3.9"

services:
  
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"


  mysql:
    image: mysql:5.7.35
    environment:
      MYSQL_DATABASE: forwa
      MYSQL_ROOT_PASSWORD: 123ezTour
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql